INSERT INTO admin (name, password) VALUES 
    ('bob feta', '12345678'),
    ('prince lee', 'abcdefgh'),
    ('one kobe', 'qwertyui'),
    ('paul patten', '98765432'),
    ('hand yolo', 'lmnopqrs');

INSERT INTO room (name, admin_id) VALUES 
    ('sauna', 1),
    ('free weights', 1),
    ('circuits room', 2),
    ('machine room', 3),
    ('machine room', 3),
    ('cardio room', 4),
    ('cardio room', 4),
    ('training room', 5),
    ('training room', 5),
    ('training room', 5);

INSERT INTO equipment (name, room_id, admin_id) VALUES
    ('dumbbells (10)', 2, 1),
    ('dumbbells (20)', 2, 1),
    ('dumbbells (30)', 2, 1),
    ('dumbbells (40)', 2, 1),
    ('dumbbells (50)', 2, 1),
    ('dumbbells (60)', 2, 1),
    ('dumbbells (70)', 2, 1),
    ('resistance band (weak)', 2, 1),
    ('resistance band (strong)', 2, 1),
    ('dumbbells (20)', 3, 2),
    ('dumbbells (30)', 3, 2),
    ('bike', 3, 2),
    ('bike', 3, 2),
    ('power rack', 4, 3),
    ('smith machine', 4, 3),
    ('cable machine', 4, 3),
    ('leg press', 4, 3),
    ('chest press', 4, 3),
    ('power rack', 5, 3),
    ('smith machine', 5, 5),
    ('cable machine', 5, 5),
    ('leg press', 5, 5),
    ('chest press', 5, 5),
    ('treadmill', 6, 5),
    ('treadmill', 6, 5),
    ('bike', 6, 5),
    ('bike', 6, 5),
    ('eliptical', 6, 4),
    ('eliptical', 6, 4),
    ('treadmill', 7, 4),
    ('treadmill', 7, 4),
    ('bike', 7, 4),
    ('bike', 7, 4),
    ('eliptical', 7, 4),
    ('eliptical', 7, 4);

    